async def invite_log_check(link) : 
    if link == "tYvhXSfGcv" : return "그늅의 놀이터 홍보 채널 홍보지"
    elif link == "dH65wdUBar" : return "갈치 서버 또는 시안 서버 홍보 채널 홍보지"
    elif link == "eJ8z9dwvnV" : return "디스코드 아카이브 홍보 채널 홍보지"
    elif link == "q6vuH4EQVQ" : return "활성화님의 서버 홍보 채널 홍보지"
    elif link == "YMyH59HRP3" : return "휴가처 홍보 채널 홍보지 또는 연합 채널 홍보지"
    elif link == "G7u5EFsZZN" : return "수원특례시 정자동 연합 채널 홍보지"
    elif link == "C5ZXawJfAu" : return "라이트샵 연합 채널 홍보지"
    elif link == "GwB7C6qZuf" : return "쿼터파인 홍보 채널 홍보지"
    elif link == "bVZggQwxun" : return "사과사과서버 홍보 채널 홍보지"
    elif link == "HfJH7kUEAH" : return "주막집 연합 채널 홍보지"
    elif link == "VNbNV9JXAM" : return "디코선생 나인서버 홍보 채널 홍보지 또는 연합 채널 홍보지 (이전 링크)"
    elif link == "PYUnqYmgtS" : return "디코선생 나인서버 홍보 채널 홍보지 또는 연합 채널 홍보지"
    elif link == "r2vSqckznP" : return "kawaii world 연합 채널 홍보지"
    elif link == "VXxJSUudEG" : return "이곳은 양지입니다 홍보 채널 홍보지"
    elif link == "tGgaRRFdfM" : return "감자 서버 연합 채널 홍보지"
    elif link == "cwudXWaWzp" : return "Rive Community 연합 채널 홍보지"
    elif link == "VMT59yEVv6" : return "루나스 연합 채널 홍보지"
    elif link == "xBnE4CGcJV" : return "내 프로필 내 소개란"
    elif link == "28CSeC5TF3" : return "하늘보리님 서버 연합 채널 홍보지"
    elif link == "VJFDuxGnRX" : return "블루 다이아몬드 커뮤니티 연합 채널 홍보지"
    elif link == "a5JQn4F5sh" : return "위키/개발 커뮤니티 메인 채널 홍보"
    elif link == "zC6uJkWbzn" : return "내 프로필 내 소개란"
    elif link == "DRFEAZWVqj" : return "내 프로필 내 소개란"
    elif link == "QVJ5nbFfDu" : return "내 프로필 내 소개란"
    elif link == "ujUrqCZ3tM" : return "내 프로필 내 소개란"
    elif link == "NxpjEFzVyA" : return "내 프로필 내 소개란"
    elif link == "VMT59yEVv6" : return "올비전 서포트 서버 홍보 채널 홍보지"
    elif link == "6pXet92r8n" : return "secret forest 연합 채널 홍보지"
    elif link == "auPkDxXBQ9" : return "cocomeda 연합 채널 홍보지"
    elif link == "3nvW9zVRku" : return "기부니가 좋아져요 홍보 채널 홍보지"
    elif link == "AcUZyzyqPT" : return "dreld 연합 채널 홍보지"
    elif link == "HGKnQK4p4p" : return "잡담을 나누자 서버 홍보 채널 홍보지"
    elif link == "rGNzq6UbkB" : return "주오중학교 연합 채널 홍보지"
    elif link == "Ee8jENgbn4" : return "리아 서버 홍보 채널 홍보지"
    elif link == "5sMNC4dEFJ" : return "Luxmens (세유 서버) 홍보 채널 홍보지"
    elif link == "M8xRYpgJdX" : return "Luxmens (세유 서버) 연합 채널 홍보지"
    elif link == "jBrfy4sJ3A" : return "하나봇 서포트 서버 (세유가 개발하는 봇 서포트 서버) 연합 채널 홍보지 (이전 링크)"
    elif link == "c2epWwqBkS" : return "하나봇 서포트 서버 (세유가 개발하는 봇 서포트 서버) 연합 채널 홍보지"
    elif link == "hJ4Cq7FT7X" : return "한디리"
    elif link == "AQQCKzpVx5" : return "하늘의 밤 연합 채널 홍보지"
    elif link == "qZPfbXtAzx" : return "unibot 서버 연합 채널 홍보지"
    elif link == "Eu2wHmt4yP" : return "the day after tomorrow 서버 연합 채널 홍보지"
    elif link == "Ty3xepGWsh" : return "마늘봇 서포트 서버 링크란에 추가한 링크"
    elif link == "NjVYgJwPAV" : return "한국철도 태그서버 홍보 채널 홍보지"
    elif link == "Tyx95yycEE" : return "디스보드"
    elif link == "aT4K7gvaCT" : return "디스보드"
    elif link == "FFW3cGxnhM" : return "디스보드"
    elif link == "6FUtVZzTd9" : return "서대문구 알피서버 연합 채널 홍보지"
    elif link == "6uQaMRG6dh" : return "the winds of liberty 연합 채널 홍보지"
    elif link == "JwswzMuN8W" : return "기부니가 좋아져요! 홍보 채널 홍보지 또는 한국 게임 서버 (블루 서버) 홍보 채널 홍보지"
    elif link == "ZTf65KzzJP" : return "Free Server 연합 채널 홍보지"
    elif link == "7Ddsqr6c4K" : return "밀냥이꺼할래? 태그 서버 홍보 채널 링크"
    elif link == "rpjwU3aCQa" : return "양파 친목방 연합 채널 홍보지"
    elif link == "arghbXNMjf" : return "아라 서포트 서버 홍보 채널 홍보지"
    elif link == "a25WaVVYQ4" : return "코섭 보이드 서버 연합 채널 홍보지"
    elif link == "QXNR5WJS9p" : return "TinyDev 연합 채널 홍보지"
    elif link == "kEbZeZTfTP" : return "하불의 믹서기 연구소 연합 채널 홍보지"
    elif link == "DhueXyrNUz" : return "무늬 서버 연합 채널 홍보지 또는 홍보 채널 홍보지"
    elif link == "24T5pHkNqp" : return "나르님 서버 연합 채널 홍보지"
    elif link == "4X4fnTCe6S" : return "전국단위 잡담방 홍보 채널 홍보지"
    elif link == "hpGrRQKB9g" : return "KR Admin Fourm 홍보지"
    else : return f"링크 {link}"